sighupio/module-monitoring

- README.md
Hi team!
Adds compatibility matrix with information about current status. This is the first compatibility matrix we deploy so, review it carefully and suggestion are always welcomed!
Current status are recovered from drone pipelines!
Thanks!
> Adds compatibility matrix structure

- README.md
Hi team,
Once #13 got merged, we should update the compatibility matrix.
Now, our latest release *(1.1.0)* was tested against 1.14, 1.15 and 1.16 cluster successfully.
Thanks!
> Add more information about compatibility

- README.md
- docs/releases/v1.1.0.md
- docs/releases/v1.2.0.md
Hi team. 
I have added some missing notes about past releases. Also i have added 1.2.0 release to the compatibility matrix.
Thanks!
> Add missing release notes

- .drone.yml
- README.md
- katalog/goldpinger/README.md
- katalog/goldpinger/deploy.yml
- katalog/goldpinger/kustomization.yaml
- katalog/goldpinger/rbac.yml
- katalog/goldpinger/sm.yml
- katalog/grafana/dashboards/goldpinger.json
- katalog/grafana/deploy.yml
- katalog/grafana/kustomization.yaml
- katalog/tests/tests.bats
Hi team!
As you know, we have used [goldpinger](https://github.com/bloomberg/goldpinger) in a real environment provided us a good view about the network situation of the Kubernetes cluster. As it was an useful utility, we considered to include it in this monitoring module.
Thanks!
> Goldpinger

- .drone.yml
- katalog/tests/grafana-ldap-auth/kustomize-project/kustomization.yaml
- katalog/tests/grafana-ldap-auth/kustomize-project/ldap-config/ldap.toml
- katalog/tests/grafana-ldap-auth/kustomize-project/patches/grafana-ldap.yaml
- katalog/tests/grafana-ldap-auth/ldap-server/ldap-server.yaml
- katalog/tests/grafana-ldap-auth/ldap-server/sighup.io-groups.ldif
- katalog/tests/grafana-ldap.sh
Hi team. 
I've added an example about how to configure LDAP grafana integration as an E2E Test.
I am also writing docs around it in the Documentation Portal. WIP
You can see the pipeline here: http://ci.sighup.io/sighupio/fury-kubernetes-monitoring/744/3/3
Feel free to ask whatever doubt you can face.
Part of: https://trello.com/c/birBocdm
> Add LDAP Grafana integration Example

- docs/releases/v1.7.0.md
- katalog/grafana/dashboards/kong.json
- katalog/grafana/deploy.yml
- katalog/grafana/kustomization.yaml
Hi guys, i tested and added this dashboard on Grafana to monitor Kong ingress controller
> Kong ingress controller dashboard added on grafana katalog

- .bumpversion.cfg
- .drone.yml
- README.md
- docs/releases/v1.8.0.md
- examples/alertmanager-configuration/Furyfile.yml
- examples/alertmanager-operated-deployment/Furyfile.yml
- examples/grafana-add-dashboard/Furyfile.yml
- examples/grafana-configuration/Furyfile.yml
- examples/grafana-remove-dashboard/Furyfile.yml
- examples/prometheus-additionalScrapes/Furyfile.yml
- examples/prometheus-alertmanager-externalUrl/Furyfile.yml
- examples/prometheus-externalLabels/Furyfile.yml
- examples/prometheus-operated-deployment/Furyfile.yml
- examples/prometheus-operated-nodeSelector/Furyfile.yml
- examples/prometheus-rules/Furyfile.yml
- examples/serviceMonitor/Furyfile.yml
This PR tests the module against two new kubernetes versions 1.17 and 1.18
Thanks!
> Release v1.8.0. Supporting 1.17 and 1.18

- README.md
- docs/releases/v1.10.2.md
- katalog/prometheus-operated/rules.yml
> Add NodeMachineIDCollision alert

- docs/releases/unreleased.md
- katalog/configs/bases/default/kustomization.yaml
> Add missing namespace in default base configurations

- katalog/alertmanager-operated/deploy.yml
- katalog/goldpinger/kustomization.yaml
- katalog/grafana/kustomization.yaml
- katalog/kube-proxy-metrics/kustomization.yaml
- katalog/kube-state-metrics/kustomization.yaml
- katalog/metrics-server/kustomization.yaml
- katalog/node-exporter/kustomization.yaml
- katalog/prometheus-operated/deploy.yml
- katalog/prometheus-operator/deploy.yml
- katalog/prometheus-operator/kustomization.yaml
- katalog/tests/grafana-ldap-auth/ldap-server/ldap-server.yaml
- katalog/thanos/thanos-components/thanos-compact/kustomization.yaml
- katalog/thanos/thanos-components/thanos-query/kustomization.yaml
- katalog/thanos/thanos-components/thanos-rule/kustomization.yaml
- katalog/thanos/thanos-components/thanos-store/kustomization.yaml
> Update registry to registry.sighup.io

- README.md
The link points to logging compatibility matrix, I fixed with the correct one
> Fix compatibility matrix link

- .drone.yml
- README.md
- docs/COMPATIBILITY_MATRIX.md
- docs/releases/v1.14.2.md
- katalog/thanos/thanos-components/thanos-store/thanos-storage-secret.yaml
- katalog/x509-exporter/daemonset.yml
- katalog/x509-exporter/deployment.yml
> [BUGFIX] - x509 exporter listen address

- katalog/prometheus-operated/README.md
- katalog/prometheus-operated/deploy.yml
as requested in the issue number 89, this will add the default RetentionSize as 80% of the default storage associated.
> chore ( #89): add RetentionSize

- examples/prometheus-rules/add-alert.yml
- katalog/alertmanager-operated/alertmanager.tmpl
- katalog/configs/kubeadm/rules.yml
- katalog/prometheus-operated/kube-prometheus-rules.yml
> Backport fixes to Alertmanager template and alerts annotations to v1.12.x

- .drone.yml
- docs/releases/v1.12.4.md
- katalog/thanos/thanos-components/thanos-store/thanos-storage-secret.yaml
> Add v1.12.4 release notes

- .drone.yml
- README.md
- docs/releases/v1.13.1.md
- katalog/thanos/thanos-components/thanos-store/thanos-storage-secret.yaml
> Add v1.13.1 release notes and align CI to other release branches

- .drone.yml
- README.md
- docs/COMPATIBILITY_MATRIX.md
- docs/releases/v1.14.3.md
> Add v1.14.3 release notes and align CI to other release branches

- README.md
- docs/CONTRIBUTING.md
- docs/releases/v2.0.0.md
- examples/alertmanager-operated-deployment/README.md
change remaining references to the master branch that we renamed to main.
> chore: change references to master branch with main

- README.md
- docs/COMPATIBILITY_MATRIX.md
- docs/releases/v2.0.1.md
- examples/alertmanager-configuration/Furyfile.yml
- examples/alertmanager-operated-deployment/Furyfile.yml
- examples/blackbox-exporter-probe/Furyfile.yml
- examples/grafana-add-dashboard/Furyfile.yml
- examples/grafana-configuration/Furyfile.yml
- examples/prometheus-additionalScrapes/Furyfile.yml
- examples/prometheus-alertmanager-externalUrl/Furyfile.yml
- examples/prometheus-externalLabels/Furyfile.yml
- examples/prometheus-operated-deployment/Furyfile.yml
- examples/prometheus-operated-nodeSelector/Furyfile.yml
- examples/prometheus-rules/Furyfile.yml
- examples/serviceMonitor/Furyfile.yml
The aim of this PR is to prepare for v2.0.1 release.
In details:
- added v2.0.1 release notes
- updated compatibility matrix
- updated main README
- updated examples Furyfiles
> Prepare v2.0.1 release

- docs/releases/v2.1.0.md
- katalog/kube-proxy-metrics/README.md
- katalog/kube-proxy-metrics/kustomization.yaml
> FEAT: update kube proxy metrics to the latest stable version and test it with k8s 1.25

- .drone.yml
> Feat/add 1.27 tests

- katalog/minio-ha/MAINTENANCE.values.yaml
- katalog/minio-ha/kustomization.yaml
minio/minio -> RELEASE.2024-10-13T13-34-11Z
minio/mc -> RELEASE.2024-10-08T09-37-26Z
> feat(katalog,minio-ha):update minio/minio and minio/mc

- README.md
- docs/CONTRIBUTING.md
- docs/releases/v3.3.0.md
update README, Release notes and other related files to prepare for releasing version 3.3.0 of the module.
> docs/v3.3.0: prepare docs for release

- katalog/aks-sm/MAINTENANCE.md
- katalog/alertmanager-operated/MAINTENANCE.md
- katalog/blackbox-exporter/MAINTENANCE.md
- katalog/configs/kubeadm/README.md
- katalog/configs/kubeadm/rules.yml
- katalog/eks-sm/MAINTENANCE.md
- katalog/gke-sm/MAINTENANCE.md
- katalog/grafana/MAINTENANCE.md
- katalog/kube-state-metrics/MAINTENANCE.md
- katalog/kubeadm-sm/MAINTENANCE.md
- katalog/node-exporter/MAINTENANCE.md
- katalog/prometheus-adapter/MAINTENANCE.md
- katalog/prometheus-operated/MAINTENANCE.md
- katalog/prometheus-operator/MAINTENANCE.md
- utils/pull-upstream.sh
- Remove noisy CPUThrottling alert (as specified in maintenance guide).
- Update Maintenance Guides.
- Linting kubeadm README.
> fix(prometheus-operated): alerts according maintenance guide

- docs/releases/unreleased.md
- katalog/prometheus-adapter/MAINTENANCE.md
- katalog/prometheus-adapter/apiService.yaml
- katalog/prometheus-adapter/clusterRole.yaml
- katalog/prometheus-adapter/clusterRoleAggregatedMetricsReader.yaml
- katalog/prometheus-adapter/clusterRoleBinding.yaml
- katalog/prometheus-adapter/clusterRoleBindingDelegator.yaml
- katalog/prometheus-adapter/clusterRoleServerResources.yaml
- katalog/prometheus-adapter/configMap.yaml
- katalog/prometheus-adapter/deployment.yaml
- katalog/prometheus-adapter/kustomization.yaml
- utils/pull-upstream.sh
- values/prometheus-adapter.yml
add custom.metrics.k8s.io/v1beta2 APIService
Closes:
https://github.com/sighupio/fury-kubernetes-monitoring/issues/191
Relates:
Added `v1beta1.custom.metrics.k8s.io APIService` APIService
None
None
> fix(prometheus-adapter): add custom.metrics.k8s.io/v1beta2 APIService

- katalog/grafana/MAINTENANCE.md
- katalog/grafana/deployment.yaml
- katalog/grafana/kustomization.yaml
- katalog/grafana/patches/grafana-probes.yaml
Reviewing Grafana probes.
Adding readiness probe default values and introducing liveness probe for Grafana.
No expected breaking changes.
> feat: Grafana probes
