sighupio/module-monitoring

.drone.yml
Hi team, 
Applying this merge request, new test are triggered against three different kubernetes cluster versions.
Now we can say that the current package supports three different kubernetes versions. Tested using own CI system (drone).
Thanks!
=> Add kubernetes 1.14,1.15 and 1.16 tests

katalog/kube-state-metrics/README.md, katalog/kube-state-metrics/deploy.yml, katalog/kube-state-metrics/kustomization.yaml, katalog/kube-state-metrics/rbac.yml, katalog/kube-state-metrics/sm.yml
The aim of this PR is to update kube-state-metrics to v1.8.0.
Please note that I explicitely ignored the new `kube-state-metrics` sharding/autosharding mechanism but I kept the `addon-resizer` sidecar.
If we want, we can address the sharding/autosharding feature in a separate PR once it becomes more stable.
=> Update kube-state-metrics to v1.8.0

.drone.yml, README.md, katalog/tests/tests.bats
Hi team.
The idea of this pull requests is to **activate old test** refactoring some of them to certify that our monitoring module is compatible with `kubernetes` versions `1.14`, `1.15` and `1.16`.
But... We found that it's not compatible with `1.16` because of api version deprecations in Kubernetes `1.16`.
It could be resolved if we update the prometheus-operator version from `0.29` to >`0.30`.
https://github.com/coreos/prometheus-operator/blob/master/CHANGELOG.md#0300--2019-05-10
There is also a new changed required by kubernetes > 1.14 that fails in kubernetes 1.16 *(thanks @lnovara)*:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#action-required-2
~~I will try to add a "test" to certify we are fully compatible with 1.16. Do you think is worthy?~~
I will try …
=> Adding new test. Marking module version 1.1.0 incompatible with Kubernetes 1.16

README.md, katalog/grafana/dashboards/kubernetes-deployments.json, katalog/grafana/dashboards/kubernetes-nodes.json, katalog/grafana/dashboards/kubernetes-pods.json, katalog/grafana/dashboards/kubernetes-statefulsets.json, katalog/prometheus-operated/rules.yml, katalog/prometheus-operator/deploy.yml
Hi team!
I have adapted this module to be compatible with kubernetes 1.16.
As a recap:
1. Modified grafana dashboards (queries)
2. Modified alerts rules (queries)
3. Upgraded prometheus-operator from 0.29 -> 0.30
This changes was caused by the kubernetes api version deprecations.
All queries has been tested against a local environment. 
Thanks!
=> Add 1.16 compatibility

README.md, docs/releases/v1.3.0.md
Hi team. 
I wanted to release a new monitoring module version. I increased a minor version because we include new features (goldpinger). 
Once this PR got merged, it's needed to create a git tag in the master branch.
```bash
$ git pull origin master
$ git tag v1.3.0
$ git push --tags
```
Thanks!
=> Add release docs 1.3.0

.bumpversion.cfg, .drone.yml, README.md, docs/releases/v1.5.0.md, examples/alertmanager-configuration/Furyfile.yml, examples/alertmanager-operated-deployment/Furyfile.yml, examples/grafana-add-dashboard/Furyfile.yml, examples/grafana-configuration/Furyfile.yml, examples/grafana-remove-dashboard/Furyfile.yml, examples/prometheus-additionalScrapes/Furyfile.yml, examples/prometheus-alertmanager-externalUrl/Furyfile.yml, examples/prometheus-externalLabels/Furyfile.yml, examples/prometheus-operated-deployment/Furyfile.yml, examples/prometheus-operated-nodeSelector/Furyfile.yml, examples/prometheus-rules/Furyfile.yml, examples/serviceMonitor/Furyfile.yml, katalog/node-exporter/deploy.yml, katalog/prometheus-operated/rules.yml, katalog/tests/tests.sh
The aim of this PR is to add a metric to keep track of machine ID and an alert that would fire whenever two or more nodes share the same machine ID.
Summary of changes:
- enabled node_exporter's textfile collector
- added `systemd_machine_id` metric
- added `NodeMachineIDCollision` alert.
Closes: sighupio/fury-kubernetes-monitoring#21
=> Add metric to keep track of systemd machine ID

.bumpversion.cfg, README.md, docs/releases/v1.6.1.md, examples/alertmanager-configuration/Furyfile.yml, examples/alertmanager-operated-deployment/Furyfile.yml, examples/grafana-add-dashboard/Furyfile.yml, examples/grafana-configuration/Furyfile.yml, examples/grafana-remove-dashboard/Furyfile.yml, examples/prometheus-additionalScrapes/Furyfile.yml, examples/prometheus-alertmanager-externalUrl/Furyfile.yml, examples/prometheus-externalLabels/Furyfile.yml, examples/prometheus-operated-deployment/Furyfile.yml, examples/prometheus-operated-nodeSelector/Furyfile.yml, examples/prometheus-rules/Furyfile.yml, examples/serviceMonitor/Furyfile.yml, katalog/grafana/dashboards/calico.json, katalog/grafana/kustomization.yaml
Hi team!
This PR is part of a bigger task: `Replace Networking Dashboard` as we moved from weave to calico.
This PR adds a dashboard to visualize metrics exposed by: https://github.com/sighupio/fury-kubernetes-networking/pull/11
It looks like:
The metrics displayed are:
- Active Local Endpoints
- Active Local Policies
- Active Local Selectors
- Active Local Tags
- Cluster Host Endpoints
- Cluster Workload Endpoints
- Cluster Hosts
- Active IP Sets
- Active IP Table Chains
- Active IP Set Command Failures
- IP Tables Save Errors
- IP Tables Restore Errors
- Felix Resyncing Datastore
- Dataplane Failed Updates
Pipeline is passing: http://ci.sighup.io/sighupio/fury-kubernetes-monitoring/764
Trello card: https://trello.com/c/4C1uxp2m
Thanks!
=> Add calico dashboard

README.md, docs/releases/v1.4.0.md, katalog/kube-state-metrics/README.md
Closes #32.
Summary of changes:
- fixed kube-state-metrics version in READMEs and release notes
- updated compatibility matrix
=> Update compatibility matrix accordingly to kube-state-metrics

README.md
There were vversion in README.md, so I put it in to correct format
=> Fix typo vversion in README.md

docs/releases/unreleased.md, katalog/grafana/dashboards/gatekeeper.json, katalog/grafana/deploy.yml, katalog/grafana/kustomization.yaml
Hello team!
This PR adds a Grafana dashboard for Gatekeeper 👮 
Please note that in order to function this dashboard depends on the following PR:
https://github.com/sighupio/fury-kubernetes-opa/pull/7
=> Add Grafana dashboard for OPA Gatekeeper metrics

docs/releases/unreleased.md, docs/releases/v1.7.1.md, katalog/metrics-server/apiservice.yml
Fixed cert-manager annotation in metrics-server APIService in order for the CA to be correctly injected.
=> Fix cert-manager annotion in metrics-sever APIService

.drone.yml, README.md, docs/releases/unreleased.md, docs/releases/v1.4.0.md, examples/serviceMonitor/README.md, katalog/aks-sm/README.md, katalog/alertmanager-operated/README.md, katalog/gke-sm/README.md, katalog/goldpinger/README.md, katalog/grafana/.gitignore, katalog/grafana/README.md, katalog/grafana/dashboards/kustomization.yaml, katalog/grafana/deploy.yml, katalog/grafana/kustomization.yaml, katalog/grafana/rbac.yml, katalog/kube-state-metrics/README.md, katalog/metrics-server/README.md, katalog/node-exporter/README.md, katalog/prometheus-operated/README.md, katalog/prometheus-operator/README.md, katalog/tests/grafana-ldap.sh, katalog/tests/promtool.sh, katalog/tests/tests.sh
Hi everyone 👋 !
i've implemented the `k8s-sidecar` that allow everyone to eventually inject in grafana whatever dashboard just creating a configmap in his namespace and labelling it with the label-key defined in the deployment. (look at README.md for more details)
This  make massively easier to add/remove/modify new/exisisting dashboard without blood and tears.
Looking forward for your review!
=> Grafana sidecar for loading dynamically dashboards

katalog/prometheus-operated/rules.yml
This alert is flooding us on basically every cluster without any added benefit, therefore I'm removing it.
Refs:
- sighupio/fury-kubernetes-monitoring#36
=> Remove CPUThrottlingHigh alert from prometheus-operated

docs/releases/v1.9.1.md, katalog/grafana/dashboards/kustomization.yaml
Hello, 
i tried the v1.9.0 version and i found a bug. If we change some dashboard, we will create a new configmap with a new suffix, and the grafana sidecar dashboard reloader is not able to manage this use case. 
To fix this, i added `disableNameSuffixHash: true` on the grafana configmap dashboard generation
=> Hotfixing grafana dashboard management

katalog/kubeadm-sm/rules.yml
The aim of this PR is to clean-up some alerts that were mistakenly duplicate in the 1.4.0 release.
=> Remove duplicate alerts from kubeadm-sm

katalog/aks-sm/README.md, katalog/aks-sm/apiserver.yml, katalog/aks-sm/kubelet.yml
The aim of this PR is to update the ServiceMonitors we use on AKS in order for the Grafana dashboards we shipped in 1.4 to work also on AKS. I copied them verbatim from `kubeadm-sm` package.
Refs:
- sighupio/fury-kubernetes-monitoring#30
=> Updated aks-sm ServiceMonitors

README.md, docs/releases/v1.10.3.md, katalog/configs/kubeadm/service-monitors/controller-manager.yml, katalog/configs/kubeadm/service-monitors/scheduler.yml
The aim of this PR is to switch controller-manager and scheduler ServiceMonitors to secure port in order for scraping to work correctly on Kubernetes 1.17+ kubeadm clusters where the insecure metrics serving was disabled.
The `insecureSkipVerify: true` is needed since both components rely on a self-signed server certificate to encrypt the communication while relying on Kubernetes RBAC to enforce authorization to the `/metrics` endpoint (which is covered by `bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token`)
Refs:
- https://github.com/sighupio/fury-kubernetes-monitoring/issues/51
=> Switch metrics scraping for controller-manager and scheduler to secure port

katalog/prometheus-operated/rules.yml
The aim of this PR is to remove the following duplicate alerts which were defined both in [config/kubeadm/rules.yml](https://github.com/sighupio/fury-kubernetes-monitoring/blob/master/katalog/configs/kubeadm/rules.yml) and [prometheus-operated/rules.yml](https://github.com/sighupio/fury-kubernetes-monitoring/blob/master/katalog/prometheus-operated/rules.yml):
- `KubeClientCertificateExpiration`
- `KubeSchedulerDown`
- `KubeControllerManagerDown`
I think they belong to `config/kubeadm` since managed services do not expose controller-manager and scheduler metrics endpoint, in general, do not allow the use of client certificates and self-manage kubelet certificates.
=> Remove duplicate Promethues alerts

docs/releases/unreleased.md, katalog/configs/kubeadm/README.md, katalog/configs/kubeadm/rules.yml, katalog/kubeadm-sm/README.md, katalog/prometheus-operated/rules.yml
We want to avoid getting into situations where we have too little time to renew certs on the clusters, because we were notified very late.
The certs are valid for 1 year, so 1 month expiration warning is reasonable.
Likewise, 7 day alert of critical severity is also appropriate.
Hopefully, the MR covers all relevant alerts, and updates all relevant documentation.
=> Modify the cluster cert expiration alerts to fire earlier

katalog/kube-proxy-metrics/deploy.yml
Fixes the following permission error:
```
"Error: failed to start container "kube-rbac-proxy": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "chdir to cwd ("/home/nonroot") set in config.json failed: permission denied": unknown"
```
=> Fixing the GID in kube-rbac-proxy

katalog/prometheus-operated/kube-prometheus-rules.yml
Hi everyone 👋 ,
I think that when the whole number of replicas are down the severity should be critical, not warning.
I currently saw only this that should be shifted, but if anyone else think that also other rules we currently have need the same change, please this probably is right time to do that!
Thanks!
=> changed severity when all targets are down

README.md, docs/releases/v1.12.3.md, katalog/thanos/thanos-components/thanos-store/thanos-store.yaml
Hello team 👋 ,
The flag `--experimental.enable-index-cache-postings-compression` was removed from Thanos v0.17.0, and its behaviour is now the default. We need to remove this flag otherwise Thanos will not start.
Thanos Changelog: https://github.com/thanos-io/thanos/blob/main/CHANGELOG.md#changed-8
Thanos PR: https://github.com/thanos-io/thanos/pull/3452
=> Remove experimental.enable-index-cache-postings-compression flag

docs/COMPATIBILITY_MATRIX.md
v1.14.0 has a known issue with prometheus since the adoption of the custom labels.
See:
https://github.com/sighupio/fury-kubernetes-monitoring/issues/83
=> Mark 1.14.0 as warning in compatibility matrix

katalog/prometheus-operated/deploy.yml
The change introduced in #95 adding the `retentionSize` parameter to prometheus-operated had a bug in the value.
The operator logged the following error:
```log
level=error ts=2022-07-22T10:20:22.090021694Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/k8s\" failed: creating config failed: generating config failed: invalid retentionSize value specified: units: unknown unit G in 120G"
```
The unit was wrong, it was missing a `B`.
This PR fixes the issue.
=> fix(prometheus-operated): fixes retentionSize unit

examples/prometheus-rules/add-alert.yml, katalog/alertmanager-operated/alertmanager.tmpl, katalog/configs/kubeadm/rules.yml, katalog/prometheus-operated/kube-prometheus-rules.yml
=> Backport fixes to Alertmanager template and alerts annotations to v1.13.x

.drone.yml
As per PR title.
Please note: unless we implement branch protection, anyone creating a `release-v*` branch will trigger e2e tests so maybe we should split this PR in two.
=> CI: rename from `master` to `main` and add `release-v*` branches to triggers

katalog/configs/kubeadm/service-monitors/controller-manager.yml, katalog/configs/kubeadm/service-monitors/scheduler.yml, katalog/configs/kubeadm/services/controller-manager.yml, katalog/configs/kubeadm/services/scheduler.yml
Fix port name for kube-controller-manager and kube-scheduler in ServiceMonitor defintion.
Port name was different in the Service defintition.
Fixes #109
=> fix(configs/kubeadm): fix SM port name

docs/releases/v2.0.0.md
- Fix some format issues
- Fix some linting issues
- Add command to delete metrics-server TLS secrets, otherwise cert-manager complains
- Add instructions about the new secrets needed for alertmanager's configuration
After the PR has been merged, I'll update also on GitHub the release.
=> docs(releases): improve 2.0.0 release notes

katalog/node-exporter/MAINTENANCE.md, katalog/node-exporter/daemonset.yaml, katalog/node-exporter/kustomization.yaml
set `GOMAXPROCS=1` to avoid CPU throttling in Kubernetes.
See prometheus/node_exporter#2530
Even keeping the resource limits the error hasn't repeated in +6h adding the env var.
Fixes #106
=> fix(node-exporter): add GOMAXPROCS=1

katalog/prometheus-operated/kustomization.yaml
Hi everyone 👋 !
Together with @smerlos today we've discovered that the patch `patchesJSON6902` related to ClusterRole `prometheus-k8s` is not working (at least with kustomize version `4.5.x`: ```{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:35:54Z GoOs:darwin GoArch:arm64}```), and won't be applied without any failure message or exit codes (kustomize is basically ignoring the patch without any message). 
A deployment without the patch will create a running instance of Prometheus (no CrashLoopBackOff) but it won't work because of missing permissions to several API  objects of Kubernetes.
The current branch removes the patch's namespace, which makes the patch back working.
Please let us know if there is any other information that is …
=> fix: namespace in patch will end in no patch applied

.drone.yml, katalog/node-exporter/MAINTENANCE.md, katalog/node-exporter/README.md, katalog/node-exporter/clusterRole.yaml, katalog/node-exporter/clusterRoleBinding.yaml, katalog/node-exporter/daemonset.yaml, katalog/node-exporter/kustomization.yaml, katalog/node-exporter/prometheusRule.yaml, katalog/node-exporter/service.yaml, katalog/node-exporter/serviceAccount.yaml, katalog/node-exporter/serviceMonitor.yaml
e2e tests are failing, this PR only addresses node-exporter and adds 1.25 to the CI
=> Feat: update node exporter to the latest stable version and test it with k8s 1.25

docs/releases/v2.1.0.md, katalog/blackbox-exporter/MAINTENANCE.md, katalog/blackbox-exporter/README.md, katalog/blackbox-exporter/clusterRoleBinding.yaml, katalog/blackbox-exporter/configuration.yaml, katalog/blackbox-exporter/deployment.yaml, katalog/blackbox-exporter/kustomization.yaml, katalog/blackbox-exporter/service.yaml, katalog/blackbox-exporter/serviceAccount.yaml, katalog/blackbox-exporter/serviceMonitor.yaml
As per title, updated blackbox-exporter package and tested with 1.25
=> FEAT: update blackbox exporter to the latest stable version

katalog/alertmanager-operated/MAINTENANCE.md, katalog/alertmanager-operated/alertmanagerconfig.yml
Hello! 
I propose changing the frequency of DeadMansSwitch alerts.
I suggest for group_wait, group_interval, and repeat_interval not use default values here because this alert is serving a different purpose than the others.
We totally don’t want to wait for it to be fired or hold back on repeats because we want it to go off at a more consistent rate.
=> [Alertmanager] Improve DeadMansSwitch intervals

katalog/grafana/prometheusRule.yaml
As per title, adding a specific grafana alert using kube-state-metrics metrics
=> feat: add GrafanaNotReady alert

katalog/configs/bases/coredns/dashboards/coredns.json
This PR fixes the jobname filter in CoreDNS grafana dashboard queries.
The jobName used to be `coredns` but it got changed to `kube-dns` in v2.0.0 of the module.
Also, the `coredns_dns_request_type_count_total` metric does not exists anymore, switched to `coredns_dns_requests_total`
=> fix(configs/coredns): fix jobname in CoreDNS dashboard queries

katalog/alertmanager-operated/alertmanager.yaml
This PR sets config matcher strategy to None for Alertmanager's definition, otherwise the Prometheus Operator will add to all the routes a matcher for a label `namespace=<namespace where alertmanager is running>`, breaking our routes.
Fixes #132
As you can see, now the routes don't have the namespace matcher added automatically anymore:
```console
$ zcat /etc/alertmanager/config/alertmanager.yaml.gz
global:
resolve_timeout: 5m
route:
receiver: noreceiver
group_by:
- alertname
routes:
- receiver: monitoring/deadmanswitch/healthchecks
matchers:
- alertname="DeadMansSwitch"
continue: true
group_wait: 1m
group_interval: 1m
repeat_interval: 30s
- receiver: monitoring/infra/infra
group_by:
- alertname
matchers:
- namespace=~"calico-api|calico-system|cert-manager|gatekeeper-system|ingress-nginx|k …
```
=> fix(AlertManager): set Config Matcher Strategy to None

katalog/thanos/MAINTENANCE.md, katalog/thanos/base/components/dashboards/bucket-replicate.json, katalog/thanos/base/components/dashboards/compact.json, katalog/thanos/base/components/dashboards/kustomization.yaml, katalog/thanos/base/components/dashboards/query-frontend.json, katalog/thanos/base/components/dashboards/query.json, katalog/thanos/base/components/dashboards/receive.json, katalog/thanos/base/components/dashboards/rule.json, katalog/thanos/base/components/dashboards/sidecar.json, katalog/thanos/base/components/dashboards/store.json, katalog/thanos/base/components/dashboards/thanos-overview-public_rev4.json, katalog/thanos/base/components/datasources/kustomization.yaml, katalog/thanos/base/components/ruler/statefulset.yaml, katalog/thanos/base/thanos-single/kustomization.yaml
This PR:
- Adds Grafana dashboards for Thanos components.
- Fixes alertmanager's service URL in Thanos ruler configuration.
=> feat(thanos): add grafana dashboards

katalog/thanos/thanos-minio/base/minio-ha/MAINTENANCE.md, katalog/thanos/thanos-minio/base/minio-ha/kustomization.yaml, katalog/thanos/thanos-minio/base/minio-ha/prometheusrules.yaml
Add 3 alerts for the included minio deployment: when disks are offline, when minio nodes are offline and when the available capacity is less than 10 percent.
=> feat(thanos/minio): add alerts for minio-monitoring

README.md, katalog/alertmanager-operated/dashboards/kustomization.yaml, katalog/configs/bases/coredns/kustomization.yaml, katalog/configs/bases/default/kustomization.yaml, katalog/configs/kubeadm/kustomization.yaml, katalog/grafana/MAINTENANCE.md, katalog/grafana/README.md, katalog/grafana/dashboardSources.yaml, katalog/grafana/dashboards/kustomization.yaml, katalog/grafana/patches/grafana-dashboard-sidecar.yml, katalog/grafana/patches/grafana-volumes.yaml, katalog/kube-proxy-metrics/dashboards/kustomization.yaml, katalog/kube-state-metrics/dashboards/kustomization.yaml, katalog/node-exporter/dashboards/kustomization.yaml, katalog/prometheus-operated/README.md, katalog/prometheus-operated/dashboards/kustomization.yaml, katalog/thanos/base/components/dashboards/kustomization.yaml, katalog/x509-exporter/common/dashboards/kustomization.yaml
With the number of Grafana dashboards that get deployed by default with KFD, a flat structure is not working anymore.
Grafana allows to organize the dashboards in folders. Making the discovery of dashboards easier and lowering the visual load on the user.
This PR is an attempt to improve the UX in Grafana by dynamically generating the folder structure. We are already using dynamic discovery of dashboards by loading all the configmaps that have the `grafana-sighup-dashboard` label. This PR adds logic and configuration to use the value of the `grafana-folder` configmap **annotation** to put the dashboards included in the folder defined by the annotation value.
Grafana will generate automatically the folder if it does not exist. If the annotation is not present, the dashboards will end up in …
=> feat(grafana): add folder generation

katalog/grafana/MAINTENANCE.md, katalog/grafana/dashboards/fury-cluster-overview.json, katalog/grafana/dashboards/kustomization.yaml
A new dashboard has been added on Grafana which allows you to have an overview of the status of the resources (deployment, daemonset, etc) present on the cluster.
=> feat(grafana): added a custom Grafana dashboard

katalog/grafana/dashboards/fury-cluster-overview.json
use dynamic datasource `$datasource` instead of hardcoding `prometheus` as datasource in several widgets. This is useful when having other datasources like Mimir for the metrics.
=> fix(grafana/dashboards): use dynamic datasource in fury-cluster-overview

README.md, katalog/thanos/README.md
Deprecate Thanos as package in favour of Mimir for achieving HA Prometheus installations and long-term storage for metrics.
Closes https://github.com/sighupio/product-management/issues/513
=> feat(thanos): deprecate package

docs/releases/v3.3.0.md, katalog/mimir/MAINTENANCE.md, katalog/mimir/MAINTENANCE.values.yaml, katalog/mimir/README.md, katalog/mimir/deploy.yaml, katalog/mimir/kustomization.yaml
- Bump Mimir to v2.14.0 (latest from upstream), aligning it with the chart version included in #183
- Update Maintenance guide.
- Checked the release notes for 2.13.0 and 2.14.0, no changes to the config are needed.
- No special steps need to be taken for upgrading from previous version of the module, BUT **you can't upgrade directly to this version from versions including Mimir < 2.11.0**.
- Images have been synced in https://github.com/sighupio/fury-distribution-container-image-sync/pull/292
=> fix(mimir): bump to v2.14.0

katalog/x509-exporter/MAINTENANCE.md, katalog/x509-exporter/README.md, katalog/x509-exporter/daemonset/base/kustomization.yaml, katalog/x509-exporter/deployment/kustomization.yaml
This PR is part of the monitoring module upgrade for the fury 1.32 distribution release. It solves the issue https://github.com/sighupio/product-management/issues/622 
It bumps the x509-exporter image to v3.18.1 and adds a missing `MAINTENANCE.md` file. 
The modifications have been both manually and automatically in a local environment using the drone pipeline. The quickest way is launching the e2e pipeline for the target Kubernetes version (in this case, 1.32) skipping the last step for cluster deletion `delete-kind-cluster` (just comment it temporarily).
```bash
drone exec --pipeline e2e-kubernetes-1.32 --trusted
```
Get the kubeconfig file and use it to inspect the status of the resources:
```bash
kind get kubeconfig --name cluster_name > /tmp/kubeconfig.yaml
export …
```
=> Feat/622 update x509 exporter for v1.32

build/builder/Dockerfile, katalog/aks-sm/README.md, katalog/alertmanager-operated/README.md, katalog/alertmanager-operated/alertmanager.yaml, katalog/alertmanager-operated/kustomization.yaml, katalog/alertmanager-operated/prometheusRule.yaml, katalog/alertmanager-operated/service.yaml, katalog/alertmanager-operated/serviceAccount.yaml, katalog/alertmanager-operated/serviceMonitor.yaml, katalog/blackbox-exporter/README.md, katalog/blackbox-exporter/clusterRoleBinding.yaml, katalog/configs/aks/README.md, katalog/configs/bases/coredns/service-monitors/coredns.yml, katalog/configs/bases/default/service-monitors/apiserver.yml, katalog/configs/bases/default/service-monitors/kubelet.yml, katalog/configs/eks/README.md, katalog/configs/gke/README.md, katalog/configs/kubeadm/README.md, katalog/eks-sm/README.md, katalog/gke-sm/README.md, katalog/grafana/README.md, katalog/karma/README.md, katalog/kube-proxy-metrics/README.md, katalog/kube-state-metrics/README.md, katalog/kubeadm-sm/README.md, katalog/node-exporter/README.md, katalog/prometheus-adapter/README.md, katalog/prometheus-operated/README.md, katalog/prometheus-operator/README.md
This PR is part of the monitoring module upgrade for the fury 1.32 distribution release. It solves the issue https://github.com/sighupio/product-management/issues/620
- It bumps the alertmanager image to v0.27.0
- A bugfix in the helper dockerfile
- Adjustments in the README.md files in the packages
The modifications have been both manually and automatically in a local environment using the drone pipeline. The quickest way is launching the e2e pipeline for the target Kubernetes version (in this case, 1.32) skipping the last step for cluster deletion `delete-kind-cluster` (just comment it temporarily).
```bash
drone exec --pipeline e2e-kubernetes-1.32 --trusted
```
Get the kubeconfig file and use it to inspect the status of the resources:
```bash
kind get kubeconfig --name cluster_name > …
```
=> Feat/620 update kube prometheus stack for v1.32

katalog/minio-ha/MAINTENANCE.md, katalog/minio-ha/README.md, katalog/minio-ha/deploy.yaml, katalog/minio-ha/kustomization.yaml
This PR is part of the monitoring module upgrade for the fury 1.32 distribution release. It solves the issue https://github.com/sighupio/product-management/issues/623
Updates minio to RELEASE.2025-02-28T09-55-16Z
Some minor changes
=> Feat/623 update minio for 1.32

.drone.yml, katalog/tests/grafana-ldap-auth/kustomize-project/kustomization.yaml, katalog/tests/tests.sh
This PR is part of the monitoring module upgrade for the fury 1.32 distribution release. It solves the issue https://github.com/sighupio/product-management/issues/624
Adds the 1.32 e2e test and remove the 1.28
Fixes the `grafana-ldap-auth` test to support kustomization 5.6
=> Feat/624 update e2e tests to include v1.32
